package kitchen;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class Expr {
  interface Visitor<R> {
    R visitIngredientExpr(Ingredient expr);
    R visitQuantityExpr(Quantity expr);
  }
  static class Ingredient extends Expr {
    Ingredient(Token tok) {
      this.tok = tok;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitIngredientExpr(this);
    }

    final Token tok;

    @Override
    public String toString() {
      return "Ingredient(" + tok + ")";
    }
  }
  static class Quantity extends Expr {
    Quantity(double amount, Token unit, Expr ingr) {
      this.amount = amount;
      this.unit = unit;
      this.ingr = ingr;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitQuantityExpr(this);
    }

    final double amount;
    final Token unit;
    final Expr ingr;

    @Override
    public String toString() {
      return "Quantity(" + amount + ", " + unit + ", " + ingr + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
