package kitchen;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class Stmt {
  interface Visitor<R> {
    R visitDefineStmt(Define stmt);
    R visitAssignStmt(Assign stmt);
    R visitIfStmt(If stmt);
    R visitWhileStmt(While stmt);
    R visitMixStmt(Mix stmt);
    R visitShakeStmt(Shake stmt);
    R visitRecipeStmt(Recipe stmt);
    R visitServeStmt(Serve stmt);
    R visitPrintStmt(Print stmt);
  }
  static class Define extends Stmt {
    Define(Token keyword) {
      this.keyword = keyword;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitDefineStmt(this);
    }

    final Token keyword;

    @Override
    public String toString() {
      return "Define(" + keyword + ")";
    }
  }
  static class Assign extends Stmt {
    Assign(Token cont, Expr object) {
      this.cont = cont;
      this.object = object;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitAssignStmt(this);
    }

    final Token cont;
    final Expr object;

    @Override
    public String toString() {
      return "Assign(" + cont + ", " + object + ")";
    }
  }
  static class If extends Stmt {
    If(Expr condition, Stmt thenBranch, Stmt elseBranch) {
      this.condition = condition;
      this.thenBranch = thenBranch;
      this.elseBranch = elseBranch;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitIfStmt(this);
    }

    final Expr condition;
    final Stmt thenBranch;
    final Stmt elseBranch;

    @Override
    public String toString() {
      return "If(" + condition + ", " + thenBranch + ", " + elseBranch + ")";
    }
  }
  static class While extends Stmt {
    While(List<Stmt> body, Expr condition) {
      this.body = body;
      this.condition = condition;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWhileStmt(this);
    }

    final List<Stmt> body;
    final Expr condition;

    @Override
    public String toString() {
      return "While(" + body + ", " + condition + ")";
    }
  }
  static class Mix extends Stmt {
    Mix(Token cont) {
      this.cont = cont;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitMixStmt(this);
    }

    final Token cont;

    @Override
    public String toString() {
      return "Mix(" + cont + ")";
    }
  }
  static class Shake extends Stmt {
    Shake(Token cont) {
      this.cont = cont;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitShakeStmt(this);
    }

    final Token cont;

    @Override
    public String toString() {
      return "Shake(" + cont + ")";
    }
  }
  static class Recipe extends Stmt {
    Recipe(Token name, List<Token> params, List<Stmt> body) {
      this.name = name;
      this.params = params;
      this.body = body;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitRecipeStmt(this);
    }

    final Token name;
    final List<Token> params;
    final List<Stmt> body;

    @Override
    public String toString() {
      return "Recipe(" + name + ", " + params + ", " + body + ")";
    }
  }
  static class Serve extends Stmt {
    Serve(Expr value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitServeStmt(this);
    }

    final Expr value;

    @Override
    public String toString() {
      return "Serve(" + value + ")";
    }
  }
  static class Print extends Stmt {
    Print(Expr value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitPrintStmt(this);
    }

    final Expr value;

    @Override
    public String toString() {
      return "Print(" + value + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
