package kitchen;

// This file is generated. Do not edit it directly.
// Generated by GenerateAST.java

import java.util.List;

abstract class Stmt {
  interface Visitor<R> {
    R visitDefineStmt(Define stmt);
    R visitDeclareStmt(Declare stmt);
    R visitIfStmt(If stmt);
    R visitWhileStmt(While stmt);
    R visitAssignStmt(Assign stmt);
    R visitReturnStmt(Return stmt);
    R visitPrintStmt(Print stmt);
  }
  static class Define extends Stmt {
    Define(Token keyword) {
      this.keyword = keyword;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitDefineStmt(this);
    }

    final Token keyword;

    @Override
    public String toString() {
      return "Define(" + keyword + ")";
    }
  }
  static class Declare extends Stmt {
    Declare(Token keyword, Expr object, Token Identifier) {
      this.keyword = keyword;
      this.object = object;
      this.Identifier = Identifier;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitDeclareStmt(this);
    }

    final Token keyword;
    final Expr object;
    final Token Identifier;

    @Override
    public String toString() {
      return "Declare(" + keyword + ", " + object + ", " + Identifier + ")";
    }
  }
  static class If extends Stmt {
    If(Expr condition, Stmt thenBranch, Stmt elseBranch) {
      this.condition = condition;
      this.thenBranch = thenBranch;
      this.elseBranch = elseBranch;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitIfStmt(this);
    }

    final Expr condition;
    final Stmt thenBranch;
    final Stmt elseBranch;

    @Override
    public String toString() {
      return "If(" + condition + ", " + thenBranch + ", " + elseBranch + ")";
    }
  }
  static class While extends Stmt {
    While(Expr condition, Stmt body) {
      this.condition = condition;
      this.body = body;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitWhileStmt(this);
    }

    final Expr condition;
    final Stmt body;

    @Override
    public String toString() {
      return "While(" + condition + ", " + body + ")";
    }
  }
  static class Assign extends Stmt {
    Assign(Token cont, Expr object) {
      this.cont = cont;
      this.object = object;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitAssignStmt(this);
    }

    final Token cont;
    final Expr object;

    @Override
    public String toString() {
      return "Assign(" + cont + ", " + object + ")";
    }
  }
  static class Return extends Stmt {
    Return(Expr value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitReturnStmt(this);
    }

    final Expr value;

    @Override
    public String toString() {
      return "Return(" + value + ")";
    }
  }
  static class Print extends Stmt {
    Print(Expr value) {
      this.value = value;
    }

    @Override
    <R> R accept(Visitor<R> visitor) {
      return visitor.visitPrintStmt(this);
    }

    final Expr value;

    @Override
    public String toString() {
      return "Print(" + value + ")";
    }
  }

  abstract <R> R accept(Visitor<R> visitor);
}
