package tool;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.List;

public class GenerateAST {
    public static void main(String[] args) throws IOException {
        // if (args.length != 1) {
        //     System.err.println("Usage: GenerateAST <output directory>");
        //     System.exit(64);
        // }
        // String outputDir = args[0];
        String outputDir = ".\\kitchen\\";

        defineAst(outputDir, "Expr", Arrays.asList(
                "Ingredient : Token tok",
                "Container  : Token tok",
                "Top        : Expr cont",
                "Rest       : Expr cont",
                "Empty      : Expr cont, boolean not",
                "Quantity   : double amount, Token unit, Expr ingr",
                "Literal    : Object value"
        ));

        defineAst(outputDir, "Stmt", Arrays.asList(
                "Define     : Token keyword",
                "Assign     : Token cont, Expr object",
                "If         : Expr condition, Stmt thenBranch, Stmt elseBranch",
                "While      : List<Stmt> body, Expr condition",
                "Mix        : Token cont",
                "Shake      : Token cont",
                "Return     : Expr value",
                "Print      : Expr value"

        ));
    }

    private static void defineAst(
            String outputDir, String baseName, List<String> types) throws IOException {
        String path = outputDir + "/" + baseName + ".java";
        PrintWriter writer = new PrintWriter(path);

        writer.println("package kitchen;");
        writer.println();
        writer.println("// This file is generated. Do not edit it directly.");
        writer.println("// Generated by GenerateAST.java");
        writer.println();
        writer.println("import java.util.List;");
        writer.println();
        writer.println("abstract class " + baseName + " {");

        defineVisitor(writer, baseName, types);

        // The AST classes.
        for (String type : types) {
            String className = type.split(":")[0].trim();
            String fields = "";
            if (type.split(":").length > 1) { fields = type.split(":")[1].trim(); }
            defineType(writer, baseName, className, fields);
        }

        // The base accept() method
        writer.println();
        writer.println("  abstract <R> R accept(Visitor<R> visitor);");

        writer.println("}");
        writer.close();
    }

    private static void defineVisitor(PrintWriter writer, String baseName, List<String> types) {
        writer.println("  interface Visitor<R> {");

        for (String type: types) {
            String typeName = type.split(":")[0].trim();
            writer.println("    R visit" + typeName + baseName + "(" + typeName + " " + baseName.toLowerCase() + ");");
        }

        writer.println("  }");
    }
        

    private static void defineType(PrintWriter writer, String baseName, String className, String fieldList) {
        writer.println("  static class " + className + " extends " + baseName + " {");

        // Constructor.
        writer.print("    " + className + "(");
        String[] fields = fieldList.split(", ");
        System.out.println("fields: " + Arrays.toString(fields) + " | " + fields.length);
        
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].equals("")) { continue; }
            String[] parts = fields[i].trim().split(" ");
            String name = parts[1];
            writer.print(parts[0] + " " + name);
            if (i < fields.length - 1) {
                writer.print(", ");
            }
        }
        writer.println(") {");

        // Store parameters in fields.
        for (String field : fields) {
            if (field.equals("")) { continue; }
            String[] parts = field.trim().split(" ");
            String name = parts[1];
            writer.println("      this." + name + " = " + name + ";");
        }
        writer.println("    }");

        // Visitor pattern.
        writer.println();
        writer.println("    @Override");
        writer.println("    <R> R accept(Visitor<R> visitor) {");
        writer.println("      return visitor.visit" + className + baseName + "(this);");
        writer.println("    }");
        writer.println();

        // Fields.
        for (String field : fields) {
            if (field.equals("")) { continue; }
            writer.println("    final " + field.trim() + ";");
        }

        writer.println();
        writer.println("    @Override");
        writer.println("    public String toString() {");
        // implement a toString() method that returns the class name and the fields
        writer.print("      return \"" + className + "(\"");
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].equals("")) { writer.print(" + "); continue; }
            String[] parts = fields[i].trim().split(" ");
            String name = parts[1];
            writer.print(" + " + name + " + ");
            if (i < fields.length - 1) {
                writer.print("\", \"");
            }
        }
        writer.println("\")\";");
        writer.println("    }");
        writer.println("  }");
    }
}